/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Application = IDL.Record({
  'id' : IDL.Text,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'jobId' : IDL.Text,
  'workerPrincipal' : UserId,
});
export const EmployerProfileInput = IDL.Record({
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
});
export const Rating = IDL.Record({
  'createdAt' : Timestamp,
  'comment' : IDL.Opt(IDL.Text),
  'stars' : IDL.Nat,
  'fromPrincipal' : UserId,
});
export const EmployerProfile = IDL.Record({
  'principal' : UserId,
  'completedHires' : IDL.Nat,
  'businessName' : IDL.Text,
  'ratings' : IDL.Vec(Rating),
  'description' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'activeJobCount' : IDL.Nat,
});
export const PaymentSessionInput = IDL.Record({
  'jobId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const PaymentSession = IDL.Record({
  'status' : PaymentStatus,
  'employerPrincipal' : UserId,
  'createdAt' : Timestamp,
  'jobId' : IDL.Text,
  'sessionId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const WorkerProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'availability' : IDL.Bool,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});
export const WorkerProfile = IDL.Record({
  'bio' : IDL.Text,
  'completedJobs' : IDL.Nat,
  'principal' : UserId,
  'displayName' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'ratings' : IDL.Vec(Rating),
  'availability' : IDL.Bool,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'totalEarnings' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Text,
  'status' : JobStatus,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'timing' : IDL.Text,
  'employerPrincipal' : UserId,
  'createdAt' : Timestamp,
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'payAmount' : IDL.Nat,
  'category' : IDL.Text,
  'urgent' : IDL.Bool,
  'applicationCount' : IDL.Nat,
  'location' : IDL.Text,
  'workerCount' : IDL.Nat,
});
export const JobFilter = IDL.Record({
  'status' : IDL.Opt(JobStatus),
  'category' : IDL.Opt(IDL.Text),
  'urgent' : IDL.Opt(IDL.Bool),
});
export const JobInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'timing' : IDL.Text,
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'payAmount' : IDL.Nat,
  'category' : IDL.Text,
  'urgent' : IDL.Bool,
  'location' : IDL.Text,
  'workerCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'applyToJob' : IDL.Func([IDL.Text], [IDL.Opt(Application)], []),
  'createEmployerProfile' : IDL.Func(
      [EmployerProfileInput],
      [EmployerProfile],
      [],
    ),
  'createPaymentSession' : IDL.Func(
      [PaymentSessionInput],
      [PaymentSession],
      [],
    ),
  'createWorkerProfile' : IDL.Func([WorkerProfileInput], [WorkerProfile], []),
  'getApplicationsForJob' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
  'getEmployerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(EmployerProfile)],
      ['query'],
    ),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
  'getJobs' : IDL.Func(
      [JobFilter, IDL.Nat, IDL.Nat],
      [IDL.Vec(Job)],
      ['query'],
    ),
  'getJobsByEmployer' : IDL.Func([UserId], [IDL.Vec(Job)], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], []),
  'getPaymentSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentSession)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func([UserId], [IDL.Opt(WorkerProfile)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'markJobComplete' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Job)], []),
  'postJob' : IDL.Func([JobInput], [Job], []),
  'respondToApplication' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Opt(Application)],
      [],
    ),
  'submitRating' : IDL.Func(
      [UserId, IDL.Bool, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateEmployerProfile' : IDL.Func(
      [EmployerProfileInput],
      [IDL.Opt(EmployerProfile)],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Text, PaymentStatus],
      [IDL.Opt(PaymentSession)],
      [],
    ),
  'updateWorkerProfile' : IDL.Func(
      [WorkerProfileInput],
      [IDL.Opt(WorkerProfile)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Application = IDL.Record({
    'id' : IDL.Text,
    'status' : ApplicationStatus,
    'appliedAt' : Timestamp,
    'jobId' : IDL.Text,
    'workerPrincipal' : UserId,
  });
  const EmployerProfileInput = IDL.Record({
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
  });
  const Rating = IDL.Record({
    'createdAt' : Timestamp,
    'comment' : IDL.Opt(IDL.Text),
    'stars' : IDL.Nat,
    'fromPrincipal' : UserId,
  });
  const EmployerProfile = IDL.Record({
    'principal' : UserId,
    'completedHires' : IDL.Nat,
    'businessName' : IDL.Text,
    'ratings' : IDL.Vec(Rating),
    'description' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'activeJobCount' : IDL.Nat,
  });
  const PaymentSessionInput = IDL.Record({
    'jobId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const PaymentSession = IDL.Record({
    'status' : PaymentStatus,
    'employerPrincipal' : UserId,
    'createdAt' : Timestamp,
    'jobId' : IDL.Text,
    'sessionId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const WorkerProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'availability' : IDL.Bool,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  const WorkerProfile = IDL.Record({
    'bio' : IDL.Text,
    'completedJobs' : IDL.Nat,
    'principal' : UserId,
    'displayName' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'ratings' : IDL.Vec(Rating),
    'availability' : IDL.Bool,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'totalEarnings' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  const JobStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : IDL.Text,
    'status' : JobStatus,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'timing' : IDL.Text,
    'employerPrincipal' : UserId,
    'createdAt' : Timestamp,
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'payAmount' : IDL.Nat,
    'category' : IDL.Text,
    'urgent' : IDL.Bool,
    'applicationCount' : IDL.Nat,
    'location' : IDL.Text,
    'workerCount' : IDL.Nat,
  });
  const JobFilter = IDL.Record({
    'status' : IDL.Opt(JobStatus),
    'category' : IDL.Opt(IDL.Text),
    'urgent' : IDL.Opt(IDL.Bool),
  });
  const JobInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'timing' : IDL.Text,
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'payAmount' : IDL.Nat,
    'category' : IDL.Text,
    'urgent' : IDL.Bool,
    'location' : IDL.Text,
    'workerCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'applyToJob' : IDL.Func([IDL.Text], [IDL.Opt(Application)], []),
    'createEmployerProfile' : IDL.Func(
        [EmployerProfileInput],
        [EmployerProfile],
        [],
      ),
    'createPaymentSession' : IDL.Func(
        [PaymentSessionInput],
        [PaymentSession],
        [],
      ),
    'createWorkerProfile' : IDL.Func([WorkerProfileInput], [WorkerProfile], []),
    'getApplicationsForJob' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
    'getEmployerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
    'getJobs' : IDL.Func(
        [JobFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(Job)],
        ['query'],
      ),
    'getJobsByEmployer' : IDL.Func([UserId], [IDL.Vec(Job)], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], []),
    'getPaymentSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentSession)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'markJobComplete' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Job)], []),
    'postJob' : IDL.Func([JobInput], [Job], []),
    'respondToApplication' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Opt(Application)],
        [],
      ),
    'submitRating' : IDL.Func(
        [UserId, IDL.Bool, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateEmployerProfile' : IDL.Func(
        [EmployerProfileInput],
        [IDL.Opt(EmployerProfile)],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Text, PaymentStatus],
        [IDL.Opt(PaymentSession)],
        [],
      ),
    'updateWorkerProfile' : IDL.Func(
        [WorkerProfileInput],
        [IDL.Opt(WorkerProfile)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };