/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : string,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'jobId' : string,
  'workerPrincipal' : UserId,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface EmployerProfile {
  'principal' : UserId,
  'completedHires' : bigint,
  'businessName' : string,
  'ratings' : Array<Rating>,
  'description' : string,
  'logoUrl' : [] | [string],
  'activeJobCount' : bigint,
}
export interface EmployerProfileInput {
  'businessName' : string,
  'description' : string,
  'logoUrl' : [] | [string],
}
export interface Job {
  'id' : string,
  'status' : JobStatus,
  'title' : string,
  'duration' : string,
  'timing' : string,
  'employerPrincipal' : UserId,
  'createdAt' : Timestamp,
  'skillsRequired' : Array<string>,
  'description' : string,
  'payAmount' : bigint,
  'category' : string,
  'urgent' : boolean,
  'applicationCount' : bigint,
  'location' : string,
  'workerCount' : bigint,
}
export interface JobFilter {
  'status' : [] | [JobStatus],
  'category' : [] | [string],
  'urgent' : [] | [boolean],
}
export interface JobInput {
  'title' : string,
  'duration' : string,
  'timing' : string,
  'skillsRequired' : Array<string>,
  'description' : string,
  'payAmount' : bigint,
  'category' : string,
  'urgent' : boolean,
  'location' : string,
  'workerCount' : bigint,
}
export type JobStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'completed' : null };
export interface PaymentSession {
  'status' : PaymentStatus,
  'employerPrincipal' : UserId,
  'createdAt' : Timestamp,
  'jobId' : string,
  'sessionId' : string,
  'amount' : bigint,
}
export interface PaymentSessionInput { 'jobId' : string, 'amount' : bigint }
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null };
export interface Rating {
  'createdAt' : Timestamp,
  'comment' : [] | [string],
  'stars' : bigint,
  'fromPrincipal' : UserId,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface WorkerProfile {
  'bio' : string,
  'completedJobs' : bigint,
  'principal' : UserId,
  'displayName' : string,
  'hourlyRate' : bigint,
  'ratings' : Array<Rating>,
  'availability' : boolean,
  'avatarUrl' : [] | [string],
  'totalEarnings' : bigint,
  'skills' : Array<string>,
}
export interface WorkerProfileInput {
  'bio' : string,
  'displayName' : string,
  'hourlyRate' : bigint,
  'availability' : boolean,
  'avatarUrl' : [] | [string],
  'skills' : Array<string>,
}
export interface _SERVICE {
  'applyToJob' : ActorMethod<[string], [] | [Application]>,
  'createEmployerProfile' : ActorMethod<
    [EmployerProfileInput],
    EmployerProfile
  >,
  'createPaymentSession' : ActorMethod<[PaymentSessionInput], PaymentSession>,
  'createWorkerProfile' : ActorMethod<[WorkerProfileInput], WorkerProfile>,
  'getApplicationsForJob' : ActorMethod<[string], Array<Application>>,
  'getEmployerProfile' : ActorMethod<[UserId], [] | [EmployerProfile]>,
  'getJob' : ActorMethod<[string], [] | [Job]>,
  'getJobs' : ActorMethod<[JobFilter, bigint, bigint], Array<Job>>,
  'getJobsByEmployer' : ActorMethod<[UserId], Array<Job>>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getPaymentSession' : ActorMethod<[string], [] | [PaymentSession]>,
  'getWorkerProfile' : ActorMethod<[UserId], [] | [WorkerProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'markJobComplete' : ActorMethod<[string, string], [] | [Job]>,
  'postJob' : ActorMethod<[JobInput], Job>,
  'respondToApplication' : ActorMethod<[string, boolean], [] | [Application]>,
  'submitRating' : ActorMethod<
    [UserId, boolean, bigint, [] | [string]],
    boolean
  >,
  'updateEmployerProfile' : ActorMethod<
    [EmployerProfileInput],
    [] | [EmployerProfile]
  >,
  'updatePaymentStatus' : ActorMethod<
    [string, PaymentStatus],
    [] | [PaymentSession]
  >,
  'updateWorkerProfile' : ActorMethod<
    [WorkerProfileInput],
    [] | [WorkerProfile]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];