/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Rating {
    createdAt: Timestamp;
    comment?: string;
    stars: bigint;
    fromPrincipal: UserId;
}
export interface Application {
    id: string;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    jobId: string;
    workerPrincipal: UserId;
}
export interface JobInput {
    title: string;
    duration: string;
    timing: string;
    skillsRequired: Array<string>;
    description: string;
    payAmount: bigint;
    category: string;
    urgent: boolean;
    location: string;
    workerCount: bigint;
}
export interface PaymentSession {
    status: PaymentStatus;
    employerPrincipal: UserId;
    createdAt: Timestamp;
    jobId: string;
    sessionId: string;
    amount: bigint;
}
export interface JobFilter {
    status?: JobStatus;
    category?: string;
    urgent?: boolean;
}
export interface PaymentSessionInput {
    jobId: string;
    amount: bigint;
}
export type UserId = Principal;
export interface Job {
    id: string;
    status: JobStatus;
    title: string;
    duration: string;
    timing: string;
    employerPrincipal: UserId;
    createdAt: Timestamp;
    skillsRequired: Array<string>;
    description: string;
    payAmount: bigint;
    category: string;
    urgent: boolean;
    applicationCount: bigint;
    location: string;
    workerCount: bigint;
}
export interface WorkerProfile {
    bio: string;
    completedJobs: bigint;
    principal: UserId;
    displayName: string;
    hourlyRate: bigint;
    ratings: Array<Rating>;
    availability: boolean;
    avatarUrl?: string;
    totalEarnings: bigint;
    skills: Array<string>;
}
export interface EmployerProfileInput {
    businessName: string;
    description: string;
    logoUrl?: string;
}
export interface WorkerProfileInput {
    bio: string;
    displayName: string;
    hourlyRate: bigint;
    availability: boolean;
    avatarUrl?: string;
    skills: Array<string>;
}
export interface EmployerProfile {
    principal: UserId;
    completedHires: bigint;
    businessName: string;
    ratings: Array<Rating>;
    description: string;
    logoUrl?: string;
    activeJobCount: bigint;
}
export enum ApplicationStatus {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum JobStatus {
    closed = "closed",
    open = "open",
    completed = "completed"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed"
}
export interface backendInterface {
    applyToJob(jobId: string): Promise<Application | null>;
    createEmployerProfile(input: EmployerProfileInput): Promise<EmployerProfile>;
    createPaymentSession(input: PaymentSessionInput): Promise<PaymentSession>;
    createWorkerProfile(input: WorkerProfileInput): Promise<WorkerProfile>;
    getApplicationsForJob(jobId: string): Promise<Array<Application>>;
    getEmployerProfile(principal: UserId): Promise<EmployerProfile | null>;
    getJob(jobId: string): Promise<Job | null>;
    getJobs(filter: JobFilter, offset: bigint, limit: bigint): Promise<Array<Job>>;
    getJobsByEmployer(employerPrincipal: UserId): Promise<Array<Job>>;
    getMyApplications(): Promise<Array<Application>>;
    getPaymentSession(sessionId: string): Promise<PaymentSession | null>;
    getWorkerProfile(principal: UserId): Promise<WorkerProfile | null>;
    isAdmin(): Promise<boolean>;
    markJobComplete(jobId: string, applicationId: string): Promise<Job | null>;
    postJob(input: JobInput): Promise<Job>;
    respondToApplication(applicationId: string, accept: boolean): Promise<Application | null>;
    submitRating(targetPrincipal: UserId, isWorker: boolean, stars: bigint, comment: string | null): Promise<boolean>;
    updateEmployerProfile(input: EmployerProfileInput): Promise<EmployerProfile | null>;
    updatePaymentStatus(sessionId: string, status: PaymentStatus): Promise<PaymentSession | null>;
    updateWorkerProfile(input: WorkerProfileInput): Promise<WorkerProfile | null>;
}
import type { Application as _Application, ApplicationStatus as _ApplicationStatus, EmployerProfile as _EmployerProfile, EmployerProfileInput as _EmployerProfileInput, Job as _Job, JobFilter as _JobFilter, JobStatus as _JobStatus, PaymentSession as _PaymentSession, PaymentStatus as _PaymentStatus, Rating as _Rating, Timestamp as _Timestamp, UserId as _UserId, WorkerProfile as _WorkerProfile, WorkerProfileInput as _WorkerProfileInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyToJob(arg0: string): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEmployerProfile(arg0: EmployerProfileInput): Promise<EmployerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployerProfile(to_candid_EmployerProfileInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_EmployerProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployerProfile(to_candid_EmployerProfileInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_EmployerProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPaymentSession(arg0: PaymentSessionInput): Promise<PaymentSession> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentSession(arg0);
                return from_candid_PaymentSession_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentSession(arg0);
            return from_candid_PaymentSession_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWorkerProfile(arg0: WorkerProfileInput): Promise<WorkerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkerProfile(to_candid_WorkerProfileInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_WorkerProfile_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkerProfile(to_candid_WorkerProfileInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_WorkerProfile_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationsForJob(arg0: string): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForJob(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForJob(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployerProfile(arg0: UserId): Promise<EmployerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployerProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployerProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobs(arg0: JobFilter, arg1: bigint, arg2: bigint): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobs(to_candid_JobFilter_n29(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobs(to_candid_JobFilter_n29(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByEmployer(arg0: UserId): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByEmployer(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByEmployer(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentSession(arg0: string): Promise<PaymentSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentSession(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentSession(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerProfile(arg0: UserId): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async markJobComplete(arg0: string, arg1: string): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markJobComplete(arg0, arg1);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markJobComplete(arg0, arg1);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async postJob(arg0: JobInput): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.postJob(arg0);
                return from_candid_Job_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postJob(arg0);
            return from_candid_Job_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async respondToApplication(arg0: string, arg1: boolean): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToApplication(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToApplication(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRating(arg0: UserId, arg1: boolean, arg2: bigint, arg3: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0, arg1, arg2, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0, arg1, arg2, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateEmployerProfile(arg0: EmployerProfileInput): Promise<EmployerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployerProfile(to_candid_EmployerProfileInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployerProfile(to_candid_EmployerProfileInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePaymentStatus(arg0: string, arg1: PaymentStatus): Promise<PaymentSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n37(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n37(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateWorkerProfile(arg0: WorkerProfileInput): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerProfile(to_candid_WorkerProfileInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerProfile(to_candid_WorkerProfileInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApplicationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_EmployerProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployerProfile): EmployerProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentSession_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentSession): PaymentSession {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Rating_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rating): Rating {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerProfile): WorkerProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Application]): Application | null {
    return value.length === 0 ? null : from_candid_Application_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployerProfile]): EmployerProfile | null {
    return value.length === 0 ? null : from_candid_EmployerProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentSession]): PaymentSession | null {
    return value.length === 0 ? null : from_candid_PaymentSession_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerProfile]): WorkerProfile | null {
    return value.length === 0 ? null : from_candid_WorkerProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Timestamp;
    comment: [] | [string];
    stars: bigint;
    fromPrincipal: _UserId;
}): {
    createdAt: Timestamp;
    comment?: string;
    stars: bigint;
    fromPrincipal: UserId;
} {
    return {
        createdAt: value.createdAt,
        comment: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.comment)),
        stars: value.stars,
        fromPrincipal: value.fromPrincipal
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    employerPrincipal: _UserId;
    createdAt: _Timestamp;
    jobId: string;
    sessionId: string;
    amount: bigint;
}): {
    status: PaymentStatus;
    employerPrincipal: UserId;
    createdAt: Timestamp;
    jobId: string;
    sessionId: string;
    amount: bigint;
} {
    return {
        status: from_candid_PaymentStatus_n16(_uploadFile, _downloadFile, value.status),
        employerPrincipal: value.employerPrincipal,
        createdAt: value.createdAt,
        jobId: value.jobId,
        sessionId: value.sessionId,
        amount: value.amount
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    completedJobs: bigint;
    principal: _UserId;
    displayName: string;
    hourlyRate: bigint;
    ratings: Array<_Rating>;
    availability: boolean;
    avatarUrl: [] | [string];
    totalEarnings: bigint;
    skills: Array<string>;
}): {
    bio: string;
    completedJobs: bigint;
    principal: UserId;
    displayName: string;
    hourlyRate: bigint;
    ratings: Array<Rating>;
    availability: boolean;
    avatarUrl?: string;
    totalEarnings: bigint;
    skills: Array<string>;
} {
    return {
        bio: value.bio,
        completedJobs: value.completedJobs,
        principal: value.principal,
        displayName: value.displayName,
        hourlyRate: value.hourlyRate,
        ratings: from_candid_vec_n10(_uploadFile, _downloadFile, value.ratings),
        availability: value.availability,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.avatarUrl)),
        totalEarnings: value.totalEarnings,
        skills: value.skills
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _JobStatus;
    title: string;
    duration: string;
    timing: string;
    employerPrincipal: _UserId;
    createdAt: _Timestamp;
    skillsRequired: Array<string>;
    description: string;
    payAmount: bigint;
    category: string;
    urgent: boolean;
    applicationCount: bigint;
    location: string;
    workerCount: bigint;
}): {
    id: string;
    status: JobStatus;
    title: string;
    duration: string;
    timing: string;
    employerPrincipal: UserId;
    createdAt: Timestamp;
    skillsRequired: Array<string>;
    description: string;
    payAmount: bigint;
    category: string;
    urgent: boolean;
    applicationCount: bigint;
    location: string;
    workerCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n27(_uploadFile, _downloadFile, value.status),
        title: value.title,
        duration: value.duration,
        timing: value.timing,
        employerPrincipal: value.employerPrincipal,
        createdAt: value.createdAt,
        skillsRequired: value.skillsRequired,
        description: value.description,
        payAmount: value.payAmount,
        category: value.category,
        urgent: value.urgent,
        applicationCount: value.applicationCount,
        location: value.location,
        workerCount: value.workerCount
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ApplicationStatus;
    appliedAt: _Timestamp;
    jobId: string;
    workerPrincipal: _UserId;
}): {
    id: string;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    jobId: string;
    workerPrincipal: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n4(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        jobId: value.jobId,
        workerPrincipal: value.workerPrincipal
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    completedHires: bigint;
    businessName: string;
    ratings: Array<_Rating>;
    description: string;
    logoUrl: [] | [string];
    activeJobCount: bigint;
}): {
    principal: UserId;
    completedHires: bigint;
    businessName: string;
    ratings: Array<Rating>;
    description: string;
    logoUrl?: string;
    activeJobCount: bigint;
} {
    return {
        principal: value.principal,
        completedHires: value.completedHires,
        businessName: value.businessName,
        ratings: from_candid_vec_n10(_uploadFile, _downloadFile, value.ratings),
        description: value.description,
        logoUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.logoUrl)),
        activeJobCount: value.activeJobCount
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    completed: null;
}): JobStatus {
    return "closed" in value ? JobStatus.closed : "open" in value ? JobStatus.open : "completed" in value ? JobStatus.completed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "completed" in value ? ApplicationStatus.completed : "rejected" in value ? ApplicationStatus.rejected : "accepted" in value ? ApplicationStatus.accepted : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rating>): Array<Rating> {
    return value.map((x)=>from_candid_Rating_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n25(_uploadFile, _downloadFile, x));
}
function to_candid_EmployerProfileInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployerProfileInput): _EmployerProfileInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_JobFilter_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobFilter): _JobFilter {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_WorkerProfileInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerProfileInput): _WorkerProfileInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    hourlyRate: bigint;
    availability: boolean;
    avatarUrl?: string;
    skills: Array<string>;
}): {
    bio: string;
    displayName: string;
    hourlyRate: bigint;
    availability: boolean;
    avatarUrl: [] | [string];
    skills: Array<string>;
} {
    return {
        bio: value.bio,
        displayName: value.displayName,
        hourlyRate: value.hourlyRate,
        availability: value.availability,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        skills: value.skills
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: JobStatus;
    category?: string;
    urgent?: boolean;
}): {
    status: [] | [_JobStatus];
    category: [] | [string];
    urgent: [] | [boolean];
} {
    return {
        status: value.status ? candid_some(to_candid_JobStatus_n31(_uploadFile, _downloadFile, value.status)) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        urgent: value.urgent ? candid_some(value.urgent) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessName: string;
    description: string;
    logoUrl?: string;
}): {
    businessName: string;
    description: string;
    logoUrl: [] | [string];
} {
    return {
        businessName: value.businessName,
        description: value.description,
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none()
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    closed: null;
} | {
    open: null;
} | {
    completed: null;
} {
    return value == JobStatus.closed ? {
        closed: null
    } : value == JobStatus.open ? {
        open: null
    } : value == JobStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
